CREATE DATABASE rkis;

\c rkis

CREATE TABLE IF NOT EXISTS smartphone
(
    id                  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    brand               character varying(50) NOT NULL,
    model               character varying(50) NOT NULL,
    operating_system    character varying(20) NOT NULL,
    storage_capacity_gb INT,
    price_usd           NUMERIC(10, 2)
);
CREATE TABLE IF NOT EXISTS users
(
    id                  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username            varchar NOT NULL,
    u_password          varchar NOT NULL,
    u_role              varchar NOT NULL
);